apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wordpress-cluster
  region: eu-west-1

managedNodeGroups:
  - name: managed
    labels: { role: workers }
    instanceTypes: ["t3.medium"]
    amiFamily: AmazonLinux2023
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    subnets:
      - "subnet-0a11215793634e586"
      - "subnet-0c9437da80f288a45"
    privateNetworking: true

