apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/angelov-g/sc-eks-wordpress-georgi.git
    targetRevision: HEAD
    path: apps/wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true
