apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-credentials
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: wordpress-credentials
    creationPolicy: Owner
  data:
    - secretKey: wordpress-password
      remoteRef:
        key: wordpress/credentials
        property: wordpressPassword
    - secretKey: mariadb-root-password
      remoteRef:
        key: wordpress/credentials
        property: mariadbRootPassword
    - secretKey: mariadb-password
      remoteRef:
        key: wordpress/credentials
        property: mariadbPassword
