apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-credentials
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: wordpress-credentials
    creationPolicy: Owner
  data:
    - secretKey: wordpressPassword
      remoteRef:
        key: wordpress/credentials
        property: wordpressPassword
    - secretKey: mariadbRootPassword
      remoteRef:
        key: wordpress/credentials
        property: mariadbRootPassword
    - secretKey: mariadbPassword
      remoteRef:
        key: wordpress/credentials
        property: mariadbPassword
