apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-credentials
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: wordpress-credentials
    creationPolicy: Owner
  data:
    - secretKey: wordpress-password
      remoteRef:
        key: wordpress/credentials
        property: wordpress-password
    - secretKey: db-host
      remoteRef:
        key: wordpress/credentials
        property: db-host
    - secretKey: db-user
      remoteRef:
        key: wordpress/credentials
        property: db-user
    - secretKey: db-password
      remoteRef:
        key: wordpress/credentials
        property: db-password
    - secretKey: db-name
      remoteRef:
        key: wordpress/credentials
        property: db-name
