apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
  namespace: wordpress
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: wordpress # Namespace is required even though it's in "default" namespace.
    name: s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region eu-west-1
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: wordpress-media # Must be unique
    volumeAttributes:
      bucketName: wordpress-media-876595225247
