apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-s3-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: wordpress-s3-pv
