apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-s3-pv
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    name: wordpress-s3-pvc
    namespace: wordpress
  mountOptions:
    - allow-delete
    - region eu-west-1
  csi:
    driver: s3.csi.aws.com
    volumeHandle: wordpress-s3-pv
    volumeAttributes:
      bucketName: wordpress-media-876595225247
      authenticationSource: driver

