wordpressUsername: admin
wordpressPassword: "wppassword"
wordpressEmail: georgi@example.com

wordpressScheme: https
wordpressBlogName: "My WordPress Site"

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  ingressClassName: alb
  hostname: wordpress.g.sevc.link
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:876595225247:certificate/054a619a-2c01-4ddb-834a-a79606c47c26"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"

mariadb:
  auth:
    rootPassword: "rootdbpassword"
    password: "dbpassword"
  primary:
    persistence:
      enabled: true
      size: 10Gi

persistence:
  enabled: true
  size: 10Gi
